-- MySQL Script generated by MySQL Workbench (Ajustado para XAMPP/MariaDB)
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BancoAcademia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BancoAcademia` DEFAULT CHARACTER SET utf8 ;
USE `BancoAcademia` ;

-- -----------------------------------------------------
-- Table `BancoAcademia`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`planos` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `duracao_meses` INT NOT NULL,
  PRIMARY KEY (`id_plano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoAcademia`.`instrutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`instrutores` (
  `id_instrutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `especialidade` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_instrutor`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoAcademia`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`alunos` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `planos_id_plano` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_alunos_planos1_idx` (`planos_id_plano` ASC),
  CONSTRAINT `fk_alunos_planos1`
    FOREIGN KEY (`planos_id_plano`)
    REFERENCES `BancoAcademia`.`planos` (`id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoAcademia`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`turmas` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `nome_atividade` VARCHAR(50) NOT NULL,
  `horario` TIME NOT NULL,
  `dias_semana` VARCHAR(50) NOT NULL,
  `instrutores_id_instrutor` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_turmas_instrutores1_idx` (`instrutores_id_instrutor` ASC),
  CONSTRAINT `fk_turmas_instrutores1`
    FOREIGN KEY (`instrutores_id_instrutor`)
    REFERENCES `BancoAcademia`.`instrutores` (`id_instrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoAcademia`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`matriculas` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `data_inscricao` DATE NOT NULL,
  `alunos_id_aluno` INT NOT NULL,
  `turmas_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_matriculas_alunos1_idx` (`alunos_id_aluno` ASC),
  INDEX `fk_matriculas_turmas1_idx` (`turmas_id_turma` ASC),
  CONSTRAINT `fk_matriculas_alunos1`
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `BancoAcademia`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_turmas1`
    FOREIGN KEY (`turmas_id_turma`)
    REFERENCES `BancoAcademia`.`turmas` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


USE `BancoAcademia`;

-- 1. POVOAMENTO DA TABELA: planos
INSERT INTO `planos` (`nome`, `valor`, `duracao_meses`) VALUES
('Plano Mensal Básico', 119.90, 1),
('Plano Trimestral', 299.70, 3),
('Plano Semestral', 539.40, 6),
('Plano Anual Premium', 958.80, 12),
('Plano Student', 89.90, 1),
('Plano VIP Total', 189.90, 1),
('Plano Família (Anual)', 1798.80, 12),
('Plano Corporal Light', 99.90, 1),
('Plano Crossfit Mensal', 149.90, 1),
('Plano Terceira Idade', 79.90, 1);

-- 2. POVOAMENTO DA TABELA: instrutores
INSERT INTO `instrutores` (`nome`, `cpf`, `especialidade`, `telefone`) VALUES
('Roberto Melo', '101.202.303-11', 'Musculação', '(47) 98111-0001'),
('Patricia Andrade', '202.303.404-22', 'Spinning', '(47) 98222-0002'),
('Marcelo Ramos', '303.404.505-33', 'Crossfit', '(47) 98333-0003'),
('Vanessa Dias', '404.505.606-44', 'Pilates', '(47) 98444-0004'),
('André Luiz', '505.606.707-55', 'Muay Thai', '(47) 98555-0005'),
('Camila Farias', '606.707.808-66', 'Zumba', '(47) 98666-0006'),
('Diego Castro', '707.808.909-77', 'Calistenia', '(47) 98777-0007'),
('Larissa Machado', '808.909.000-88', 'Natação', '(47) 98888-0008'),
('Felipe Nogueira', '909.000.111-99', 'Musculação', '(47) 98999-0009'),
('Renata Silveira', '000.111.222-00', 'Yoga', '(47) 98000-0010');

-- 3. POVOAMENTO DA TABELA: alunos
INSERT INTO `alunos` (`nome`, `cpf`, `telefone`, `data_nascimento`, `planos_id_plano`) VALUES
('Lucas Silva', '111.222.333-44', '(47) 99111-1001', '1995-03-12', 1),
('Mariana Santos', '222.333.444-55', '(47) 99222-1002', '1998-07-25', 2),
('Carlos Eduardo', '333.444.555-66', '(47) 99333-1003', '1990-11-05', 3),
('Beatriz Lima', '444.555.666-77', '(47) 99444-1004', '2001-01-30', 4),
('Gabriel Oliveira', '555.666.777-88', '(47) 99555-1005', '1992-09-18', 1),
('Fernanda Costa', '666.777.888-99', '(47) 99666-1006', '1988-05-14', 2),
('Rodrigo Alves', '777.888.999-00', '(47) 99777-1007', '1996-12-08', 5),
('Juliana Pereira', '888.999.000-11', '(47) 99888-1008', '2003-04-22', 6),
('Mateus Rocha', '999.000.111-22', '(47) 99999-1009', '1985-08-19', 3),
('Aline Martins', '000.111.222-33', '(47) 99000-1010', '1999-10-02', 4);

-- 4. POVOAMENTO DA TABELA: turmas
INSERT INTO `turmas` (`nome_atividade`, `horario`, `dias_semana`, `instrutores_id_instrutor`) VALUES
('Musculação Manhã', '07:00:00', 'Seg, Quar, Sex', 1),
('Spinning Intenso', '18:30:00', 'Ter, Quin', 2),
('Crossfit WOD', '19:00:00', 'Seg, Quar, Sex', 3),
('Pilates Solo', '08:00:00', 'Ter, Quin', 4),
('Muay Thai Noite', '20:00:00', 'Seg, Quar, Sex', 5),
('Zumba Dance', '17:30:00', 'Ter, Quin', 6),
('Calistenia Avançada', '10:00:00', 'Sábados', 7),
('Natação Adulto', '06:30:00', 'Seg, Quar, Sex', 8),
('Musculação Tarde', '15:00:00', 'Seg a Sex', 9),
('Yoga Matinal', '07:30:00', 'Ter, Quin', 10);

-- 5. POVOAMENTO DA TABELA: matriculas
INSERT INTO `matriculas` (`data_inscricao`, `alunos_id_aluno`, `turmas_id_turma`) VALUES
('2024-01-10', 1, 1),
('2024-01-12', 2, 2),
('2024-01-15', 3, 3),
('2024-02-01', 4, 4),
('2024-02-05', 5, 5),
('2024-02-10', 6, 6),
('2024-02-15', 7, 7),
('2024-03-01', 8, 8),
('2024-03-05', 9, 9),
('2024-03-10', 10, 10);