-- MySQL Script generated by MySQL Workbench (Ajustado para XAMPP/MariaDB)
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BancoAcademia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BancoAcademia` DEFAULT CHARACTER SET utf8 ;
USE `BancoAcademia` ;

-- -----------------------------------------------------
-- Table `BancoAcademia`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`planos` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `duracao_meses` INT NOT NULL,
  PRIMARY KEY (`id_plano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoAcademia`.`instrutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`instrutores` (
  `id_instrutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `especialidade` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_instrutor`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoAcademia`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`alunos` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `planos_id_plano` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_alunos_planos1_idx` (`planos_id_plano` ASC),
  CONSTRAINT `fk_alunos_planos1`
    FOREIGN KEY (`planos_id_plano`)
    REFERENCES `BancoAcademia`.`planos` (`id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoAcademia`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`turmas` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `nome_atividade` VARCHAR(50) NOT NULL,
  `horario` TIME NOT NULL,
  `dias_semana` VARCHAR(50) NOT NULL,
  `instrutores_id_instrutor` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_turmas_instrutores1_idx` (`instrutores_id_instrutor` ASC),
  CONSTRAINT `fk_turmas_instrutores1`
    FOREIGN KEY (`instrutores_id_instrutor`)
    REFERENCES `BancoAcademia`.`instrutores` (`id_instrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoAcademia`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoAcademia`.`matriculas` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `data_inscricao` DATE NOT NULL,
  `alunos_id_aluno` INT NOT NULL,
  `turmas_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_matriculas_alunos1_idx` (`alunos_id_aluno` ASC),
  INDEX `fk_matriculas_turmas1_idx` (`turmas_id_turma` ASC),
  CONSTRAINT `fk_matriculas_alunos1`
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `BancoAcademia`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_turmas1`
    FOREIGN KEY (`turmas_id_turma`)
    REFERENCES `BancoAcademia`.`turmas` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;